<?php

namespace Database\Seeders;

use App\Models\MarketplaceStatus;
use Illuminate\Database\Seeder;

class MarketplaceStatusSeeder extends Seeder
{
    public function run(): void
    {
        $statuses = [
            'sanborns' => [
                [0, 'Pendientes', 1, 1],
                [1, 'Pago por confirmar', 2, 1],
                [2, 'En espera de documentos', 3, 1],
                [3, 'Embarcado', 4, 1],
                [4, 'Entregado', 5, 1],
                [5, 'Procesando pedido', 6, 0],
                [6, 'Liberado', 7, 1],
                [7, 'Cancelado', 8, 1],
                [8, 'TDC rechazada', 9, 1],
                [9, 'Por embarcar', 10, 1],
                [10, 'Pago no recibido por Paypal', 11, 1],
                [11, 'Pago recibido en Paypal NO VERIFICADO', 12, 1],
                [12, 'Esperando deposito del cliente', 13, 1],
                [13, 'Pedido de prueba', 14, 1],
                [14, 'Recogera en nuestras oficinas', 15, 0],
                [15, 'Por realizar cargo con tarjeta', 16, 0],
                [16, 'Por embarcar con Proveedor', 17, 1],
                [17, 'Solicita reembolso', 18, 1],
                [18, 'Fraude', 19, 1],
                [19, 'Reembolso realizado', 20, 1],
                [20, 'Reembolso autorizado', 21, 1],
                [21, 'En Aclaracion', 22, 1],
                [22, 'Parcialmente surtido', 23, 1],
                [23, 'Importacion en proceso', 24, 0],
                [24, 'Entregado n/conf', 25, 0],
                [25, 'Sin permiso', 26, 0],
                [26, 'Pendiente facebook', 27, 0],
                [27, 'Esperando Safetypay', 28, 1],
                [28, 'fraude_comprobado', 29, 0],
                [29, 'Pago no aceptado por banco(IF)', 30, 0],
                [31, 'Pago NO recibido en Bancanet', 31, 1],
                [32, 'Esperando confirmacion cliente', 32, 1],
                [33, 'Garant&iacute;s', 33, 0],
                [34, 'Investigaciones', 34, 0],
                [35, 'Reprocesar Pedido', 35, 0],
                [36, 'Esperando confirmacion codigo de autorizacion bancario', 36, 0],
                [37, 'Esperando confirmacion de monto cargado', 37, 1],
                [38, 'Por validar codigo de autorizacion bancario', 38, 0],
                [39, 'Por validar monto cargado', 39, 0],
                [40, 'Validacion Guia', 40, 1],
                [41, 'PlazaVIPTC por cobrar', 41, 1],
                [42, 'PlazaVIPTC esperando conf Unicard', 42, 1],
                [43, 'Paypal pagado', 43, 1],
                [44, 'Sin respuesta confirmacion', 44, 0],
                [45, 'RecargaTA', 45, 0],
                [46, 'Tc por tramitar', 46, 1],
                [47, 'En espera mercapago', 47, 1],
                [48, 'Mercapago Pagado', 48, 1],
                [49, 'Telmex validacion exitosa', 49, 1],
                [50, 'Cancelados Telmex', 50, 1],
                [51, 'Cambio de producto', 51, 0],
                [52, 'Pendiente Sears', 52, 1],
                [53, 'Pendiente Telmex', 53, 1],
                [54, 'Parcial', 54, 1],
                [55, 'Completo', 55, 1],
                [56, 'Cargar por Terminal', 56, 1],
                [57, 'Procesando por Telmex', 57, 1],
                [58, 'Procesando por Telmex', 57, 1],
                [59, 'Entregado Parcialmente', 58, 0],
                [60, 'Reembolso Parcial', 59, 1],
                [61, 'Enviado Telmex', 60, 1],
                [62, 'Transaccion Rechazada', 61, 1],
                [63, 'Transaccion Pendiente Cybersource', 62, 1],
                [64, 'Reactivado', 63, 0],
                [65, 'Reactivado', 64, 0],
                [66, 'Pedido Reactivado', 64, 1],
                [67, 'Pendiente Paypal', 65, 1],
                [68, 'Review Paypal', 66, 1],
                [69, 'Cancel Paypal', 67, 1],
                [70, 'Succes Paypal', 68, 1],
                [71, 'Aprobado Afiliacion Bancaria', 69, 0],
                [72, 'Apob. x Validar Telcel', 70, 1],
                [73, 'Enviado Telcel', 71, 1],
                [74, 'Entregado Parcial', 72, 1],
                [75, 'Pendiente Sin N.Orden', 73, 1],
                [76, 'Pendiente por Validacion Telefonica', 74, 1],
                [77, 'Cancelado por Validación Telefónica', 75, 1],
                [78, 'Validacion sin Antifraude', 76, 1],
                [79, 'En Revisión', 77, 1],
                [80, 'Con Incidencia de Sistema', 78, 1],
                [81, 'Solicita cancelacion', 79, 1],
                [82, 'Rechazado', 80, 1],
                [83, 'Validacion Guia Retorno', 81, 1],
                [84, 'Dictaminado Fraude Telmex', 82, 1],
                [85, 'Reactivacion de Pedido', 83, 1],
                [86, 'Solicita Cancelacion', 84, 1],
                [94, 'Reenviado', 87, 1],
                [98, 'Recoger en Tienda Sanborns', 85, 1],
                [99, 'Pagar y Recoger en Tienda Sanborns', 86, 1],
                [106, 'En Disputa', 106, 1],
                [111, 'Listo para recoger CYR', 107, 1],
                [112, 'Enviado a tienda B CYR', 108, 1],
                [113, 'Devuelta en tienda', 113, 1],
                [114, 'Retorno seller tienda', 114, 1],
            ],

            'sears' => [
                [0, 'Pendientes', 1, 1],
                [1, 'Pago por confirmar', 2, 1],
                [2, 'En espera de documentos', 3, 1],
                [3, 'Embarcado', 4, 1],
                [4, 'Entregado', 5, 1],
                [5, 'Procesando pedido', 6, 0],
                [6, 'Liberado', 7, 1],
                [7, 'Cancelado', 8, 1],
                [8, 'TDC rechazada', 9, 1],
                [9, 'Por embarcar', 10, 1],
                [10, 'Pago no recibido por Paypal', 11, 1],
                [11, 'Pago recibido en Paypal NO VERIFICADO', 12, 1],
                [12, 'Esperando deposito del cliente', 13, 1],
                [13, 'Pedido de prueba', 14, 1],
                [14, 'Recogera en nuestras oficinas', 15, 0],
                [15, 'Por realizar cargo con tarjeta', 16, 0],
                [16, 'Por embarcar con Proveedor', 17, 1],
                [17, 'Solicita rembolso', 18, 1],
                [18, 'Fraude', 19, 1],
                [19, 'Rembolso realizado', 20, 1],
                [20, 'Rembolso autorizado', 21, 1],
                [21, 'En Aclaracion', 22, 1],
                [22, 'Parcialmente surtido', 23, 1],
                [23, 'Importacion en proceso', 24, 0],
                [24, 'Entregado n/conf', 25, 0],
                [25, 'Sin permiso', 26, 0],
                [26, 'Pendiente facebook', 27, 0],
                [27, 'Esperando Safetypay', 28, 1],
                [28, 'fraude_comprobado', 29, 0],
                [29, 'Pago no aceptado por banco(IF)', 30, 0],
                [31, 'Pago NO recibido en Bancanet', 31, 1],
                [32, 'Esperando confirmacion cliente', 32, 1],
                [33, 'Garant&iacute;s', 33, 0],
                [34, 'Investigaciones', 34, 0],
                [35, 'Reprocesar Pedido', 35, 0],
                [36, 'Esperando confirmacion codigo de autorizacion bancario', 36, 0],
                [37, 'Esperando confirmacion de monto cargado', 37, 1],
                [38, 'Por validar codigo de autorizacion bancario', 38, 0],
                [39, 'Por validar monto cargado', 39, 0],
                [40, 'Validacion Guia', 40, 1],
                [41, 'PlazaVIPTC por cobrar', 41, 1],
                [42, 'PlazaVIPTC esperando conf Unicard', 42, 1],
                [43, 'Paypal pagado', 43, 1],
                [44, 'Sin respuesta confirmacion', 44, 0],
                [45, 'RecargaTA', 45, 0],
                [46, 'Tc por tramitar', 46, 1],
                [47, 'En espera mercapago', 47, 1],
                [48, 'Mercapago Pagado', 48, 1],
                [49, 'Telmex validacion exitosa', 49, 1],
                [50, 'Cancelados Telmex', 50, 1],
                [51, 'Cambio de producto', 51, 0],
                [52, 'Pendiente Sears', 52, 1],
                [53, 'Pendiente Telmex', 53, 1],
                [54, 'Parcial', 54, 1],
                [55, 'Completo', 55, 1],
                [56, 'Cargar por Terminal', 56, 1],
                [57, 'Procesando por Telmex', 57, 1],
                [58, 'Procesando por Telmex', 57, 1],
                [59, 'Entregado Parcialmente', 58, 0],
                [60, 'Reembolso Parcial', 59, 1],
                [61, 'Enviado Telmex', 60, 1],
                [62, 'Transaccion Rechazada', 61, 1],
                [63, 'Transaccion Pendiente Cybersource', 62, 1],
                [64, 'Reactivado', 63, 0],
                [65, 'Reactivado', 64, 0],
                [66, 'Pedido Reactivado', 64, 1],
                [67, 'Pendiente Paypal', 65, 1],
                [68, 'Review Paypal', 66, 1],
                [69, 'Cancel Paypal', 67, 1],
                [70, 'Succes Paypal', 68, 1],
                [71, 'Aprobado Afiliacion Bancaria', 69, 0],
                [72, 'Apob. x Validar Telcel', 70, 1],
                [73, 'Enviado Telcel', 71, 1],
                [74, 'Entregado Parcial', 72, 1],
                [75, 'Pendiente Sin N.Orden', 73, 1],
                [76, 'Pendiente por Validacion Telefonica', 74, 1],
                [77, 'Cancelado por Validación Telefónica', 75, 1],
                [78, 'Validacion sin Antifraude', 76, 1],
                [79, 'En Revisión', 77, 1],
                [80, 'Con Incidencia de Sistema', 78, 1],
                [81, 'Solicita cancelacion', 79, 1],
                [82, 'Rechazado', 80, 1],
                [83, 'Validacion Guia Retorno', 81, 1],
                [84, 'Dictaminado Fraude Telmex', 82, 1],
                [85, 'Reactivacion de Pedido', 83, 1],
                [86, 'Solicita Cancelacion', 84, 1],
                [87, 'Rembolso Manual', 85, 1],
                [88, 'Reenviado', 86, 1],
                [96, 'Recoger en tienda Sears', 88, 1],
                [97, 'Pagar y recoger en tienda Sears', 89, 1],
                [106, 'En Disputa', 87, 1],
                [110, 'Solicita Devolución', 110, 1],
                [111, 'Listo para recoger CYR', 90, 1],
                [112, 'Enviado a tienda B CYR', 91, 1],
                [113, 'Devuelta en tienda', 113, 1],
                [114, 'Retorno seller tienda', 114, 1],
                [115, 'Devolución no Autorizada', 115, 1],
                [116, 'Devolución Reembolsada', 116, 1],
            ],
        ];

        foreach ($statuses as $marketplace => $items) {
            foreach ($items as [$externalId, $name, $sortOrder, $visible]) {
                MarketplaceStatus::updateOrCreate(
                    [
                        'marketplace' => $marketplace,
                        'external_id' => $externalId,
                    ],
                    [
                        'name' => $name,
                        'sort_order' => $sortOrder,
                        'visible' => (bool) $visible,
                    ]
                );
            }
        }
    }
}
